config/routes.rb
Rails.application.routes.draw do
  root "reviews#index"
  resources :reviews, only: [:index, :new, :create, :edit, :update]
  resources :users do
    resources :reviews, only: [:index]
  end
  #/user/1/reviews
  resources :restaurants, only: [:index, :show] do
    resources :reviews, only: [:new]
  end

  get "/login", to: "session#new", as: "login"
  post "/login", to: "session#create"
  get "/logout", to: "session#logout", as: "logout"
  get "/auth/github/callback", to: "session#github"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  has_many :users, through: :reviews
  validates :name, presence: true, uniqueness: true

  def self.top_rated
    Restaurant.joins(:reviews).group(:restaurant_id).order("avg(rating) desc")
  end

  def rating
    sum = 0
    num = self.reviews.length
    self.reviews.each{|review| sum += review.rating}
    sum/num if self.reviews
  end

  def avg_rating
    sum = 0; total = (self.reviews.length).to_f
    self.reviews.each{|review| sum += review.rating }
    (sum/total).round(1)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates :rating, presence: true
  validates :content, presence: true
  accepts_nested_attributes_for :restaurant
  paginates_per 10

  def restaurant_attributes=(restaurant)
    self.restaurant = Restaurant.find_or_create_by(name: restaurant[:name])
    self.restaurant.update(restaurant)
  end

  def self.all_sorted
    Review.order(created_at: :desc)
  end

  def username
    self.user.username
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :restaurants, through: :reviews
  has_secure_password
  validates :password, presence: true
  validates :username, presence: true, uniqueness: true
  #validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.top_rated
    respond_to do |format|
      format.html
      format.json { render json: @restaurants }
    end
    #shows top rated restaurants
    #if logged in, you can see everything else but add restaurants, reviews, and upvote
    #if logged in, can sort by categories
  end

  def show
    restaurant = Restaurant.find(params[:id])
    render json: restaurant
  end

  private
    def find_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    #homepage: timeline of most recent reviews with restaurants
    #links to specific restaurants for all reviews
    if params[:user_id]
      @user = User.find(params[:user_id])
      @reviews = @user.reviews
    else
      @reviews = Review.all_sorted.page params[:page]
      @user = current_user
    end

  end

  def new
    if current_user.id == session[:user_id].to_i
      @restaurant = params[:restaurant_id] ? Restaurant.find(params[:restaurant_id]) : Restaurant.new
      @review = @restaurant.reviews.build
    else
      flash[:message] = "You must be logged in to make a review."
      redirect_to login_path
    end
  end

  def create
    if current_user.id == session[:user_id].to_i
      @review = Review.create(review_params)
      @review.user = current_user
      @review.save
        if @review.invalid?
          render json: {errors: @review.errors.full_messages}, status: 400
        else
          render json: @review, status: 201
        end
    else
      flash[:message] = "You must be logged in to make a review."
      redirect_to login_path
    end
  end

  private
    def review_params
      params.require(:review).permit(:rating, :content, restaurant_attributes: [:name])
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new

  end

  def create
    binding.pry
    user = User.find_by(username: session_params[:username])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:message] = "Invalid user. Please try again."
      redirect_to login_path
    end
  end

  def github
    @user = User.find_or_initialize_by(id: auth['uid']).tap do |u|
      flash[:message] = "Login successful."
      u.username = auth['info']['nickname']
      u.password = "password"
      u.save
      session[:user_id] = u.id
    end
    redirect_to :root
  end

  def logout
    session.clear
    redirect_to :root
  end

  private
    def session_params
      params.require(:session).permit(:username, :password)
    end

    def auth
     request.env['omniauth.auth']
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    #form to sign up
    @user = User.new
  end

  def create

    user = User.create(user_params)
    if user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:message] = "Invalid entry, please try again."
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user }
    end
  end


  private
    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3RestaurantReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="indigo darken-4">
      <div class="nav-wrapper">
        <a href="#" class="brand-logo left">RESTaurants</a>
        <ul class="right hide-on-med-and-down">
        <% if logged_in? %>
          <li> <%= link_to "Logout", logout_path %> </li>
          <li> <%= link_to "Find a restaurant near you!", restaurants_path %> </li>
        <% else %>
          <li> <%= link_to "Sign Up", new_user_path %> </li>
          <li> <%= link_to "Log In", login_path %> </li>
          <li> <%= link_to('Log in with Github!', '/auth/github') %> </li>
        <%end%>
        <li> <%= link_to "Homepage", root_path %> </li>
        </ul>
      </div>
    </nav>
    <%= flash[:message] %>
    <div class="container"> <%= yield %> </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h3> Top rated Restaurants </h3>

  <button id="top_restaurants_button"> Click here to see the top rated restaurants!</button>

  <div id="restaurants">

    </div>

app/views/restaurants/show.html.erb
<h1 class="center"> <%= @restaurant.name %> </h1>
<h3 class="center"> <%=@restaurant.rating%> stars average </h3>

<% @restaurant.reviews.each do |review| %>
  <p> <%= review.username%>: <%= review.rating %> stars </p>
  <div class="row">
  <p class="col s5 push-s1"> <%= review.content %> <p>
  </div>
<% end %>

<%= link_to "Click here to review this restaurant.", new_restaurant_review_path(@restaurant) %>

app/views/reviews/_form.html.erb
<%= form_for review do |f| %>
  <%= f.hidden_field :restaurant_id %>
  <%= f.label :restaurant %>
  <%= f.fields_for :restaurant do |rest|%>
    <%= rest.text_field :name %>
  <% end %>
  <br>
  <%= f.label :rating  %>
  <%= f.text_field :rating %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h3> Edit your review </h3>
<%= render partial: "reviews/form", locals: {review: @review} %>

app/views/reviews/index.html.erb
<h3 class="center"> Timeline of recent reviews<%=@user ? " for #{@user.username}" : ""%>:</h3>

<% if logged_in? %>
  <button class="review"> Add a review! </button>
<% else %>
  <p> Sign up or Log in to leave a review </p>
<% end %>

<div id="error_message"> </div>
<div id="new_review_form">
  <div>
    <%= form_tag("/reviews", method: "post", class: "review_form") do%>
      Restaurant: <%= text_field_tag "review[restaurant_attributes][name]" %>
      Rating: <%= text_field_tag "review[rating]" %>
      Content: <%= text_field_tag "review[content]" %>
      <%= submit_tag "Submit Review" %>
    <% end %>
    </div>
</div>


<ul>
  <div id="new_review"> </div>
  <% i = 0 %>
  <% @reviews.each do |review| %>
    <button class="username" data-id="<%=review.user.id %>" data-button_id="<%=i%>"> <%=review.user.username%>: </button>
    <div id="user_div-<%=i%>" class="row" > </div> <!-- adding user show page -->
    <div class="row">
      <li class="col s9 push-s1"> Restaurant: <button class="restaurant" data-id="<%= review.restaurant.id %>" data-button_id="<%=i%>"><%= review.restaurant.name%> </button> <br>
        <div id="restaurant_div-<%= i%>"> </div> <br> <!-- restaurant show page -->
      Rating: <%= review.rating %> stars <br>
      Review: <%= review.content %> </li>
    </div>
    <br>
    <% i += 1 %>
  <% end %>
</ul>
<%= paginate @reviews %>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h3>
      You did not submit a full review. Please try again.
    </h3>

    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li class="red-text"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render partial: "reviews/form", locals: {review: @review} %> 

app/views/session/new.html.erb
<%= form_for :session, url: login_path do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit "Log In"%> 
<% end %>

app/views/users/new.html.erb
<h3> Welcome New User! Please make an account </h3>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome, <%= @user.username %>! </h1>
<h2> Here are your reviews </h2>
<div class="row">
<% @user.reviews.each do |review| %>
  <div><%= review.restaurant.name %> </div>

  Rating: <%= review.rating %>
  <br>
  <%= review.content %>
  <br><br>
<% end %>
</div>
<br>
<%= link_to "Have you eaten anywhere recently? Click here to review it", new_review_path %>